name: VirtualMenu自动构建

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: 拉取仓库
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: 设置Java8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'zulu'
        cache: maven
    - name: 使用Maven构建
      run: |
        mvn -B package --file pom.xml

    - name: 获取发布信息
      id: extract
      uses: andreacomo/maven-gav-extractor@v2

    - name: 输出信息
      run: |
        echo ${{ steps.extract.outputs.group-id }}
        echo ${{ steps.extract.outputs.artifact-id }}
        echo ${{ steps.extract.outputs.version }}
        echo ${{ steps.extract.outputs.name }}
      shell: bash

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: 更新artifacts
      uses: actions/upload-artifact@v4
      with:
        path: target/*.jar
        name: VirtualMenu

    - name: 发布
      uses: softprops/action-gh-release@v2
      with:
        tag_name: V${{ steps.extract.outputs.version }}
        files: target/${{ steps.extract.outputs.name }}_v${{ steps.extract.outputs.version }}.jar
